/**
 * Spatie permission names from the API (`guard_name: api`).
 * Always use PERMISSIONS constants — never raw strings.
 *
 *   ✅ can(PERMISSIONS.USERS.LIST)
 *   ❌ can('users.list')
 */
export const PERMISSION_GUARD = 'api' as const

export const PERMISSIONS = {
  CATEGORIES: {
    LIST: 'categories.list',
    CREATE: 'categories.create',
    SHOW: 'categories.show',
    UPDATE: 'categories.update',
    REORDER: 'categories.reorder',
    DELETE: 'categories.delete',
    RESTORE: 'categories.restore',
    FORCE_DELETE: 'categories.force-delete',
  },
  ROLES: {
    LIST: 'roles.list',
    CREATE: 'roles.create',
    SHOW: 'roles.show',
    UPDATE: 'roles.update',
    DELETE: 'roles.delete',
    RESTORE: 'roles.restore',
    FORCE_DELETE: 'roles.force-delete',
  },
  ARTICLES: {
    LIST: 'articles.list',
    TRASHED: 'articles.trashed',
    CREATE: 'articles.create',
    SHOW: 'articles.show',
    UPDATE: 'articles.update',
    DELETE: 'articles.delete',
    RESTORE: 'articles.restore',
    FORCE_DELETE: 'articles.force-delete',
    ACTIVITIES: 'articles.activities',
    STATS: 'articles.stats',
    /** User-panel read history (Spatie group: Articles). */
    USER_READ_HISTORY: 'user.read-history',
  },
  TAGS: {
    LIST: 'tags.list',
    CREATE: 'tags.create',
    SHOW: 'tags.show',
    UPDATE: 'tags.update',
    DELETE: 'tags.delete',
    RESTORE: 'tags.restore',
    FORCE_DELETE: 'tags.force-delete',
  },
  SAVE_ARTICLES: {
    LIST: 'save-articles.list',
    TOGGLE: 'save-articles.toggle',
  },
  SITE_SETTINGS: {
    LIST: 'site-settings.list',
    UPDATE: 'site-settings.update',
  },
  PLANS: {
    LIST: 'plans.list',
    TRASHED: 'plans.trashed',
    CREATE: 'plans.create',
    SHOW: 'plans.show',
    UPDATE: 'plans.update',
    DELETE: 'plans.delete',
    RESTORE: 'plans.restore',
    FORCE_DELETE: 'plans.force-delete',
  },
  NOTIFICATION_PREFERENCES: {
    SHOW: 'notification-preferences.show',
    UPDATE: 'notification-preferences.update',
  },
  USER_NOTIFICATIONS: {
    LIST: 'user-notifications.list',
    MARK_READ: 'user-notifications.mark-read',
    MARK_ALL_READ: 'user-notifications.mark-all-read',
  },
  ANNOUNCEMENTS: {
    LIST: 'announcements.list',
    CREATE: 'announcements.create',
    SHOW: 'announcements.show',
    UPDATE: 'announcements.update',
    DELETE: 'announcements.delete',
    PUBLISH: 'announcements.publish',
  },
  COMMENTS: {
    CREATE: 'comments.create',
    LIST: 'comments.list',
    APPROVE: 'comments.approve',
    REJECT: 'comments.reject',
    DELETE: 'comments.delete',
  },
  CONTACT_INQUIRIES: {
    LIST: 'contact-inquiries.list',
    SHOW: 'contact-inquiries.show',
    UPDATE: 'contact-inquiries.update',
    DELETE: 'contact-inquiries.delete',
    REPLY: 'contact-inquiries.reply',
    EXPORT: 'contact-inquiries.export',
    BULK: 'contact-inquiries.bulk',
  },
  MENUS: {
    LIST: 'menus.list',
    CREATE: 'menus.create',
    SHOW: 'menus.show',
    UPDATE: 'menus.update',
    DELETE: 'menus.delete',
    RESTORE: 'menus.restore',
    FORCE_DELETE: 'menus.force-delete',
    REORDER: 'menus.reorder',
    MANAGE_LOCATIONS: 'menus.manage-locations',
    MANAGE_ITEMS: 'menus.manage-items',
  },
  CAREERS_PAGE: {
    SHOW: 'careers-page.show',
    UPDATE: 'careers-page.update',
  },
  PRIVACY_POLICY: {
    SHOW: 'privacy-policy.show',
    UPDATE: 'privacy-policy.update',
  },
  TERMS_OF_SERVICE: {
    SHOW: 'terms-of-service.show',
    UPDATE: 'terms-of-service.update',
  },
  ABOUT_US: {
    SHOW: 'about-us.show',
    UPDATE: 'about-us.update',
  },
  COOKIE_POLICY: {
    SHOW: 'cookie-policy.show',
    UPDATE: 'cookie-policy.update',
  },
  ACCESSIBILITY_STATEMENT: {
    SHOW: 'accessibility-statement.show',
    UPDATE: 'accessibility-statement.update',
  },
  ACCESSIBILITY_REPORTS: {
    LIST: 'accessibility-reports.list',
    UPDATE: 'accessibility-reports.update',
  },
  CAREER_JOBS: {
    LIST: 'career-jobs.list',
    CREATE: 'career-jobs.create',
    SHOW: 'career-jobs.show',
    UPDATE: 'career-jobs.update',
    DELETE: 'career-jobs.delete',
    RESTORE: 'career-jobs.restore',
    FORCE_DELETE: 'career-jobs.force-delete',
  },
  CAREER_APPLICATIONS: {
    LIST: 'career-applications.list',
    SHOW: 'career-applications.show',
    UPDATE: 'career-applications.update',
    DELETE: 'career-applications.delete',
    EXPORT: 'career-applications.export',
    BULK: 'career-applications.bulk',
  },
  LIVE_UPDATES: {
    LIST: 'live-updates.list',
    CREATE: 'live-updates.create',
    SHOW: 'live-updates.show',
    UPDATE: 'live-updates.update',
    DELETE: 'live-updates.delete',
  },
  MONETIZATION: {
    LIST: 'monetization.list',
    CREATE: 'monetization.create',
    UPDATE: 'monetization.update',
  },
  NAVIGATION: {
    LIST: 'navigation.list',
    CREATE: 'navigation.create',
    UPDATE: 'navigation.update',
    DELETE: 'navigation.delete',
  },
  NEWSLETTER: {
    LIST: 'newsletter.list',
    CREATE: 'newsletter.create',
    SHOW: 'newsletter.show',
    UPDATE: 'newsletter.update',
    DELETE: 'newsletter.delete',
    SEND: 'newsletter.send',
  },
  SCHEDULED_TASKS: {
    LIST: 'scheduled-tasks.list',
    RERUN: 'scheduled-tasks.rerun',
  },
  PERMISSIONS: {
    LIST: 'permissions.list',
  },
  MEDIA: {
    LIST: 'media.list',
    CREATE: 'media.create',
    SHOW: 'media.show',
    DELETE: 'media.delete',
    BULK_DELETE: 'media.bulk-delete',
    SIGNED_PARAMS: 'media.signed-params',
    TRANSFORM: 'media.transform',
  },
  USERS: {
    LIST: 'users.list',
    CREATE: 'users.create',
    PROFILE: 'users.profile',
    PROFILE_UPDATE: 'users.profile-update',
    SHOW: 'users.show',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
    ARTICLE_ACTIVITIES: 'users.article-activities',
    TWO_FACTOR_ENABLE: 'users.two-factor-enable',
    READING_ANALYTICS: 'users.reading-analytics',
  },
} as const

type LeafPermissionValues<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? { [K in keyof T]: LeafPermissionValues<T[K]> }[keyof T]
    : never

export type PermissionKey = LeafPermissionValues<typeof PERMISSIONS>

/** Spatie `group_name` keyed by permission `name`. */
export const PERMISSION_GROUP_BY_KEY: Record<PermissionKey, string> = {
  [PERMISSIONS.CATEGORIES.LIST]: 'Categories',
  [PERMISSIONS.CATEGORIES.CREATE]: 'Categories',
  [PERMISSIONS.CATEGORIES.SHOW]: 'Categories',
  [PERMISSIONS.CATEGORIES.UPDATE]: 'Categories',
  [PERMISSIONS.CATEGORIES.REORDER]: 'Categories',
  [PERMISSIONS.CATEGORIES.DELETE]: 'Categories',
  [PERMISSIONS.CATEGORIES.RESTORE]: 'Categories',
  [PERMISSIONS.CATEGORIES.FORCE_DELETE]: 'Categories',
  [PERMISSIONS.ROLES.LIST]: 'Roles',
  [PERMISSIONS.ROLES.CREATE]: 'Roles',
  [PERMISSIONS.ROLES.SHOW]: 'Roles',
  [PERMISSIONS.ROLES.UPDATE]: 'Roles',
  [PERMISSIONS.ROLES.DELETE]: 'Roles',
  [PERMISSIONS.ROLES.RESTORE]: 'Roles',
  [PERMISSIONS.ROLES.FORCE_DELETE]: 'Roles',
  [PERMISSIONS.ARTICLES.LIST]: 'Articles',
  [PERMISSIONS.ARTICLES.TRASHED]: 'Articles',
  [PERMISSIONS.ARTICLES.CREATE]: 'Articles',
  [PERMISSIONS.ARTICLES.SHOW]: 'Articles',
  [PERMISSIONS.ARTICLES.UPDATE]: 'Articles',
  [PERMISSIONS.ARTICLES.DELETE]: 'Articles',
  [PERMISSIONS.ARTICLES.RESTORE]: 'Articles',
  [PERMISSIONS.ARTICLES.FORCE_DELETE]: 'Articles',
  [PERMISSIONS.ARTICLES.ACTIVITIES]: 'Articles',
  [PERMISSIONS.ARTICLES.STATS]: 'Articles',
  [PERMISSIONS.ARTICLES.USER_READ_HISTORY]: 'Articles',
  [PERMISSIONS.TAGS.LIST]: 'Tags',
  [PERMISSIONS.TAGS.CREATE]: 'Tags',
  [PERMISSIONS.TAGS.SHOW]: 'Tags',
  [PERMISSIONS.TAGS.UPDATE]: 'Tags',
  [PERMISSIONS.TAGS.DELETE]: 'Tags',
  [PERMISSIONS.TAGS.RESTORE]: 'Tags',
  [PERMISSIONS.TAGS.FORCE_DELETE]: 'Tags',
  [PERMISSIONS.SAVE_ARTICLES.LIST]: 'Save Articles',
  [PERMISSIONS.SAVE_ARTICLES.TOGGLE]: 'Save Articles',
  [PERMISSIONS.SITE_SETTINGS.LIST]: 'Site Settings',
  [PERMISSIONS.SITE_SETTINGS.UPDATE]: 'Site Settings',
  [PERMISSIONS.PLANS.LIST]: 'Membership Plans',
  [PERMISSIONS.PLANS.TRASHED]: 'Membership Plans',
  [PERMISSIONS.PLANS.CREATE]: 'Membership Plans',
  [PERMISSIONS.PLANS.SHOW]: 'Membership Plans',
  [PERMISSIONS.PLANS.UPDATE]: 'Membership Plans',
  [PERMISSIONS.PLANS.DELETE]: 'Membership Plans',
  [PERMISSIONS.PLANS.RESTORE]: 'Membership Plans',
  [PERMISSIONS.PLANS.FORCE_DELETE]: 'Membership Plans',
  [PERMISSIONS.NOTIFICATION_PREFERENCES.SHOW]: 'Notification Preferences',
  [PERMISSIONS.NOTIFICATION_PREFERENCES.UPDATE]: 'Notification Preferences',
  [PERMISSIONS.USER_NOTIFICATIONS.LIST]: 'User Notifications',
  [PERMISSIONS.USER_NOTIFICATIONS.MARK_READ]: 'User Notifications',
  [PERMISSIONS.USER_NOTIFICATIONS.MARK_ALL_READ]: 'User Notifications',
  [PERMISSIONS.ANNOUNCEMENTS.LIST]: 'Announcements',
  [PERMISSIONS.ANNOUNCEMENTS.CREATE]: 'Announcements',
  [PERMISSIONS.ANNOUNCEMENTS.SHOW]: 'Announcements',
  [PERMISSIONS.ANNOUNCEMENTS.UPDATE]: 'Announcements',
  [PERMISSIONS.ANNOUNCEMENTS.DELETE]: 'Announcements',
  [PERMISSIONS.ANNOUNCEMENTS.PUBLISH]: 'Announcements',
  [PERMISSIONS.COMMENTS.CREATE]: 'Comments',
  [PERMISSIONS.COMMENTS.LIST]: 'Comments',
  [PERMISSIONS.COMMENTS.APPROVE]: 'Comments',
  [PERMISSIONS.COMMENTS.REJECT]: 'Comments',
  [PERMISSIONS.COMMENTS.DELETE]: 'Comments',
  [PERMISSIONS.CONTACT_INQUIRIES.LIST]: 'Contact Inquiries',
  [PERMISSIONS.CONTACT_INQUIRIES.SHOW]: 'Contact Inquiries',
  [PERMISSIONS.CONTACT_INQUIRIES.UPDATE]: 'Contact Inquiries',
  [PERMISSIONS.CONTACT_INQUIRIES.DELETE]: 'Contact Inquiries',
  [PERMISSIONS.CONTACT_INQUIRIES.REPLY]: 'Contact Inquiries',
  [PERMISSIONS.CONTACT_INQUIRIES.EXPORT]: 'Contact Inquiries',
  [PERMISSIONS.CONTACT_INQUIRIES.BULK]: 'Contact Inquiries',
  [PERMISSIONS.MENUS.LIST]: 'Menus',
  [PERMISSIONS.MENUS.CREATE]: 'Menus',
  [PERMISSIONS.MENUS.SHOW]: 'Menus',
  [PERMISSIONS.MENUS.UPDATE]: 'Menus',
  [PERMISSIONS.MENUS.DELETE]: 'Menus',
  [PERMISSIONS.MENUS.RESTORE]: 'Menus',
  [PERMISSIONS.MENUS.FORCE_DELETE]: 'Menus',
  [PERMISSIONS.MENUS.REORDER]: 'Menus',
  [PERMISSIONS.MENUS.MANAGE_LOCATIONS]: 'Menus',
  [PERMISSIONS.MENUS.MANAGE_ITEMS]: 'Menus',
  [PERMISSIONS.CAREERS_PAGE.SHOW]: 'Careers Page',
  [PERMISSIONS.CAREERS_PAGE.UPDATE]: 'Careers Page',
  [PERMISSIONS.PRIVACY_POLICY.SHOW]: 'Privacy Policy',
  [PERMISSIONS.PRIVACY_POLICY.UPDATE]: 'Privacy Policy',
  [PERMISSIONS.TERMS_OF_SERVICE.SHOW]: 'Terms of Service',
  [PERMISSIONS.TERMS_OF_SERVICE.UPDATE]: 'Terms of Service',
  [PERMISSIONS.ABOUT_US.SHOW]: 'About Us',
  [PERMISSIONS.ABOUT_US.UPDATE]: 'About Us',
  [PERMISSIONS.COOKIE_POLICY.SHOW]: 'Cookie Policy',
  [PERMISSIONS.COOKIE_POLICY.UPDATE]: 'Cookie Policy',
  [PERMISSIONS.ACCESSIBILITY_STATEMENT.SHOW]: 'Accessibility Statement',
  [PERMISSIONS.ACCESSIBILITY_STATEMENT.UPDATE]: 'Accessibility Statement',
  [PERMISSIONS.ACCESSIBILITY_REPORTS.LIST]: 'Accessibility Reports',
  [PERMISSIONS.ACCESSIBILITY_REPORTS.UPDATE]: 'Accessibility Reports',
  [PERMISSIONS.CAREER_JOBS.LIST]: 'Career Jobs',
  [PERMISSIONS.CAREER_JOBS.CREATE]: 'Career Jobs',
  [PERMISSIONS.CAREER_JOBS.SHOW]: 'Career Jobs',
  [PERMISSIONS.CAREER_JOBS.UPDATE]: 'Career Jobs',
  [PERMISSIONS.CAREER_JOBS.DELETE]: 'Career Jobs',
  [PERMISSIONS.CAREER_JOBS.RESTORE]: 'Career Jobs',
  [PERMISSIONS.CAREER_JOBS.FORCE_DELETE]: 'Career Jobs',
  [PERMISSIONS.CAREER_APPLICATIONS.LIST]: 'Career Applications',
  [PERMISSIONS.CAREER_APPLICATIONS.SHOW]: 'Career Applications',
  [PERMISSIONS.CAREER_APPLICATIONS.UPDATE]: 'Career Applications',
  [PERMISSIONS.CAREER_APPLICATIONS.DELETE]: 'Career Applications',
  [PERMISSIONS.CAREER_APPLICATIONS.EXPORT]: 'Career Applications',
  [PERMISSIONS.CAREER_APPLICATIONS.BULK]: 'Career Applications',
  [PERMISSIONS.LIVE_UPDATES.LIST]: 'Live Updates',
  [PERMISSIONS.LIVE_UPDATES.CREATE]: 'Live Updates',
  [PERMISSIONS.LIVE_UPDATES.SHOW]: 'Live Updates',
  [PERMISSIONS.LIVE_UPDATES.UPDATE]: 'Live Updates',
  [PERMISSIONS.LIVE_UPDATES.DELETE]: 'Live Updates',
  [PERMISSIONS.MONETIZATION.LIST]: 'Monetization',
  [PERMISSIONS.MONETIZATION.CREATE]: 'Monetization',
  [PERMISSIONS.MONETIZATION.UPDATE]: 'Monetization',
  [PERMISSIONS.NAVIGATION.LIST]: 'Navigation',
  [PERMISSIONS.NAVIGATION.CREATE]: 'Navigation',
  [PERMISSIONS.NAVIGATION.UPDATE]: 'Navigation',
  [PERMISSIONS.NAVIGATION.DELETE]: 'Navigation',
  [PERMISSIONS.NEWSLETTER.LIST]: 'Newsletter',
  [PERMISSIONS.NEWSLETTER.CREATE]: 'Newsletter',
  [PERMISSIONS.NEWSLETTER.SHOW]: 'Newsletter',
  [PERMISSIONS.NEWSLETTER.UPDATE]: 'Newsletter',
  [PERMISSIONS.NEWSLETTER.DELETE]: 'Newsletter',
  [PERMISSIONS.NEWSLETTER.SEND]: 'Newsletter',
  [PERMISSIONS.SCHEDULED_TASKS.LIST]: 'Scheduled Tasks',
  [PERMISSIONS.SCHEDULED_TASKS.RERUN]: 'Scheduled Tasks',
  [PERMISSIONS.PERMISSIONS.LIST]: 'Permissions',
  [PERMISSIONS.MEDIA.LIST]: 'Media',
  [PERMISSIONS.MEDIA.CREATE]: 'Media',
  [PERMISSIONS.MEDIA.SHOW]: 'Media',
  [PERMISSIONS.MEDIA.DELETE]: 'Media',
  [PERMISSIONS.MEDIA.BULK_DELETE]: 'Media',
  [PERMISSIONS.MEDIA.SIGNED_PARAMS]: 'Media',
  [PERMISSIONS.MEDIA.TRANSFORM]: 'Media',
  [PERMISSIONS.USERS.LIST]: 'Users',
  [PERMISSIONS.USERS.CREATE]: 'Users',
  [PERMISSIONS.USERS.PROFILE]: 'Users',
  [PERMISSIONS.USERS.PROFILE_UPDATE]: 'Users',
  [PERMISSIONS.USERS.SHOW]: 'Users',
  [PERMISSIONS.USERS.UPDATE]: 'Users',
  [PERMISSIONS.USERS.DELETE]: 'Users',
  [PERMISSIONS.USERS.ARTICLE_ACTIVITIES]: 'Users',
  [PERMISSIONS.USERS.TWO_FACTOR_ENABLE]: 'Users',
  [PERMISSIONS.USERS.READING_ANALYTICS]: 'Users',
}

/** All permission names in API order. */
export const ALL_PERMISSION_KEYS = Object.keys(PERMISSION_GROUP_BY_KEY) as PermissionKey[]

/**
 * Permissions used only on the user panel (not admin sidebar / AdminLayout gates).
 */
export const USER_PANEL_PERMISSION_KEYS: PermissionKey[] = [
  PERMISSIONS.SAVE_ARTICLES.LIST,
  PERMISSIONS.SAVE_ARTICLES.TOGGLE,
  PERMISSIONS.NOTIFICATION_PREFERENCES.SHOW,
  PERMISSIONS.NOTIFICATION_PREFERENCES.UPDATE,
  PERMISSIONS.USER_NOTIFICATIONS.LIST,
  PERMISSIONS.USER_NOTIFICATIONS.MARK_READ,
  PERMISSIONS.USER_NOTIFICATIONS.MARK_ALL_READ,
  PERMISSIONS.ARTICLES.USER_READ_HISTORY,
  PERMISSIONS.USERS.PROFILE,
  PERMISSIONS.USERS.PROFILE_UPDATE,
  PERMISSIONS.USERS.TWO_FACTOR_ENABLE,
  PERMISSIONS.USERS.READING_ANALYTICS,
]
